services:
  frontend:
    image: ghcr.io/alixanneraud/deez-nalyzer-frontend:latest
    environment:
      - BACKEND_URL=http://<backend>
    ports:
      - "8080:8080"

  backend:
    image: ghcr.io/alixanneraud/deez-nalyzer-backend:latest
    ports:
      - "8000:8000"
    environment:
      - SPOTIFY_CLIENT_ID=""
      - SPOTIFY_CLIENT_SECRET=""
    volumes:
      - ./data:/app/data 
      - ./cache:/home/root/.cache/huggingface/hug