version: '3.8'

services:
  frontend:
    image: ghcr.io/alixanneraud/deez-nalyzer-frontend:latest
    ports:
      - "8080:8080"

  backend:
    image: ghcr.io/alixanneraud/deez-nalyzer-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data 
      - ./cache:/home/root/.cache/huggingface/hug