name: Build and publish Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up | Checkout repository
        uses: actions/checkout@v4

      - name: Set up | Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up | Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build | Backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/alixanneraud/deez-nalyzer-backend:latest

      - name: Build | Frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/alixanneraud/deez-nalyzer-frontend:latest
